### ISSUE TITLE
Add WartRemover warning suppression to implicit instance builder

### ISSUE THREAD

**Issue by catostrophe** [manatki/derevo#27]
Please suppress WartRemover warnings as it's done in `simulacrum`:
https://github.com/mpilquist/simulacrum/blob/a88ff4dc7b5a67d312813e71a85fc32f178dbdc4/core/src/main/scala/simulacrum/typeclass.scala#L387

Not sure which particular warts should be suppressed. Adding only `ExplicitImplicitTypes` worked for me, but the list might be bigger in other cases.

**Comment by REDNBLACK** [comment]
Fixed in #72
